version: '3.8'

services:
  todo-app:
    image: ghcr.io/YOUR_USERNAME/todo-list-nodejs:latest  # Replace with your actual image path
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - mongoDbUrl=mongodb://mongo:27017/todo-list
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    depends_on:
      - todo-app
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    driver: bridge 