version: '3.8'

services:
  todo-app:
    image: "mkhattab77/privatemultiuser:v1"
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    depends_on:
      - todo-app
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    name: todo-network
    driver: bridge
